### ISSUE TITLE
"log" module doesn't work if you are not in ~/.lambdabot

### ISSUE THREAD

**Issue by abbradar** [lambdabot/lambdabot#117]
It uses relative paths when creating directories and files (i.e. "State/Log/...."), so for it to work correctly you must be in correct working directory before starting the bot.

**Comment by int-e** [comment]
(Sorry for the delay, the last two weeks have been very busy...)

In my recent refactoring of lambdabot's file handling (8d792a44adff371ee210788d56ee930f8be1d826 and 52d396ee9bff84e49eedd675bec0d8702ce06847) I didn't touch the Log module.

The reason is, I don't know what the *right* behavior is here, so I stuck to the existing one, which is what you observed: stick the log files into `./State/Log`. However there is a side effect that I didn't consider, namely that once the log module creates the `State` directory, lambdabot will not look for files in `~/.lambdabot/State` anymore. That's bad.

I see at least two options here:
 * stick the log files in `~/.lambdabot/State/Log` by default (unless `./State` exists), to match the behaviour of (other) state files
 * write the logs ino `./Log` (no `State`), and make the directory name overridable by a command line switch

Comments?

**Comment by mokus0** [comment]
For what it's worth, I have no qualms about changing things in whatever way makes sense.  This is an area of the code that has had pretty much nothing done to it for years except as necessary to keep it building.  I don't use that module but I guess if I did I'd probably want it to have some sensible default and a configurable override for that variable.

**Comment by int-e** [comment]
@abbradar do you have any preferences on this, i.e., where did you expect the log files to be stored? As mokus0 wrote, this module is not really maintained. I don't use it either.

**Comment by abbradar** [comment]
(sorry, I wanted to give my preference much earlier but forgot to answer an e-mail) I think that sticking everything to `~/.lambdabot/State/Log` would be consistent, and overridable with symlinks if anybody needs this. FWIW, I `cd` before running `lambdabot` now so I end up with this very behavior.
