### ISSUE TITLE
"log" module doesn't log user disconnects and lambdabot's own messages

### ISSUE THREAD

**Issue by abbradar** [lambdabot/lambdabot#118]
Ditto.

**Comment by int-e** [comment]
These are two separate issues.

 1. lambdabot's `Log` plugin doesn't track `QUIT` messages
 2. lambdabot has no infrastructure for informing plugins about its own messages

Neither problem is entirely trivial to fix.

 1. The IRC server sends only one `QUIT` message when a user quits; because lambdabot logs several channels separately, it would have to track the channels that the user is currently in in order to log them properly. But currently, lambdabot does not track this information (except in the `Seen` plugin, but that has its own problems...)
 2. This would require a new callback mechanisms so that plugins can register for sent messages. A possible approach would be to hook into the `send` function (cf. `Lambdabot.Monad`).

**Comment by int-e** [comment]
To me the real question is what the purpose of the `Log` plugin should be. Right now, it's a quick and dirty hack that just uses the information that is conveniently available. Personally, I don't see logging as a core functionality of lambdabot, so I don't want to work on improving this situation.

To get fully featured logging for lambdabot, I would consider running it via an IRC bouncer (znc, for example, has a plugin for logging, http://wiki.znc.in/Log).

**Comment by abbradar** [comment]
Thanks, I'll look at znc. In case I'll do the patch by myself, would you consider accepting it?

**Comment by int-e** [comment]
Yes, a patch would be welcome.

**Comment by abbradar** [comment]
Great, thanks! If you prefer, you may close this -- I'll look at this some weekend.

**Comment by int-e** [comment]
Closing this as suggested.
