### ISSUE TITLE
Evaluation does not work

### ISSUE THREAD

**Issue by Baughn** [lambdabot/lambdabot#131]
Under a clean install of GHC 7.10.2, with nothing but lambdabot and dependencies installed...

$ rm -rf .ghc .cabal
$ cabal update
$ cabal install mueval alex happy djinn lambdabot
$ lambdabot

lambdabot> > 42
[ERROR] : Main: caught (and ignoring) Enum.toEnum{Word8}: tag (8216) is outside of bounds (0,255)

**Comment by int-e** [comment]
Explanation: mueval's utf8 handling changed between mueval-0.9.1.1 and mueval-0.9.1.1.2, adding to lambdabot's unicode mess.

**Comment by int-e** [comment]
I also see that you didn't clean the .lambdabot directory. I suspect that hint/mueval produce a warning, which lambdabot then fails to display due to encoding issues.

https://github.com/lambdabot/lambdabot/commit/87445a20525bfaa082bbde94cd4b78ffec378157 is a partial fix for the problem, but still wrong (see also #111):

```
lambdabot> > foo
     Not in scope: Ã¢fooÃ¢
lambdabot> > let ä = 1 in ä
 <hint>:1:1: parse error in let binding: missing required 'in'
```

**Comment by morpheusbeing** [comment]
I have just done a complete install of haskell package on Debian Stretch, and then added lambdabot. I am running 2 instances of it, one in terminal and one in test irc channel.

The one running in the terminal works fine:
[code]
lambdabot> map (+1) [1..10]
2,3,4,5,6,7,8,9,10,11
[/code]

The one working as irc bot does not
[code]
18:37 < MorpheusB> ?map (+1) [1..10]
18:37 < ScrewLoose008> Maybe you meant: slap msg faq
[/code]

I have also tried @map command, but with same result
