### ISSUE TITLE
Strange behaviour with @unpl

### ISSUE THREAD

**Issue by LiamGoodacre** [lambdabot/lambdabot#142]
As noted here: https://github.com/23Skidoo/pointful/issues/8

~~~haskell
-- correct: `and true false` is false
> (\l r t f -> l (r t f) f) (\t f -> t) (\t f -> f)
(\ t f -> f)

-- incorrect: `and true false 1` should be `\f -> f`
> (\l r t f -> l (r t f) f) (\t f -> t) (\t f -> f) 1
(\ f -> 1)

-- incorrect: `and true false 1 0` should be `0`
> (\l r t f -> l (r t f) f) (\t f -> t) (\t f -> f) 1 0
1
~~~

**Comment by int-e** [comment]
Looking at this code is painful; it relies on generics for all its traversals, which makes it difficult to track variable names. There is this lovely comment where it does beta-reduction:

    -- TODO: avoid captures while substituting

The code gets some other things wrong as well, also due to taking too much liberty with bound variable names:

    -- equal variables in left hand sides are forbidden
    > f a = \a -> a
     f a a = a
    
    -- similar for lambda abstractions
    > \a -> \a -> a
    \a a -> a

    -- another thing that can go wrong is failing to do eta reduction:
    > \a -> b (\d -> c) a
    b (\d -> c)
    > \a -> b (\a -> c) a
    \a -> b (\a -> c) a

**Comment by int-e** [comment]
Another one:

    > \join -> join
    \ join b -> b >>= \ a -> a
