### ISSUE TITLE
Support haskell-src-exts 1.18

### ISSUE THREAD

**Issue by 23Skidoo** [lambdabot/lambdabot#146]
Unannotated AST representation [was removed](https://github.com/haskell-suite/haskell-src-exts/commit/38c2befdd07e20a268f8d6c685cca90a2992ed67) from `haskell-src-exts` in version 1.18, which means that most code using `haskell-src-exts` has to be updated to support the new version. One particular example that fails to build with h-s-e 1.18 is [`Lambdabot/Plugin/Haskell/Pointful.hs`](https://github.com/lambdabot/lambdabot/blob/master/lambdabot-haskell-plugins/src/Lambdabot/Plugin/Haskell/Pointful.hs).

Originally reported [here](https://github.com/23Skidoo/pointful/issues/10).

**Comment by int-e** [comment]
See https://github.com/lambdabot/lambdabot/commit/78a2361024724acb70bc1c12c42f3a16015bb373

Note: This uses the new [haskell-src-exts-simple](https://hackage.haskell.org/package/haskell-src-exts-simple) package, which requires ghc-7.10 or later because of its use of explicitly bidirectional pattern synonyms.

**Comment by int-e** [comment]
cf. https://github.com/int-e/haskell-src-exts-simple/issues/1 regarding support for ghc-7.8

**Comment by int-e** [comment]
5b65c4b3952dbb00f43b5e815e6755d18422ef4f and 753109e351ce041ebc42136571daef50ebe23ce5 restore compatibility with ghc-7.8
